import { Button } from '@chakra-ui/button'
import { Box, Heading, HStack, Link, Text, VStack } from '@chakra-ui/layout'
import Head from 'next/head'

import CustomLink from '../components/utils/CustomLink'

const DesignSystem = () => {
  return (
    <Box>
      <Head>
        <title>Next Chakra UI Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box p="6" maxW="600px" mx="auto">
        <VStack spacing="6" textAlign="left" align="flex-start" mb="6">
          <Heading as="h1" variant="h1">
            H1. Create and share your photo stories.
          </Heading>
          <Heading as="h2" variant="h2">
            H2. Basic • Pro • Business
          </Heading>
          <Heading as="h3" variant="h3">
            H3. No Photo Upload Limit
          </Heading>
          <Heading as="h4" variant="h4">
            H4. View the stories
          </Heading>
          <Text>
            Text. We provide design templates to ensure your stories look
            terrific. Easily add photos, text, embed maps and media from other
            networks. Then share your story with everyone.
          </Text>
        </VStack>
        <HStack spacing="6" p="6" mb="6" border="1px">
          <Button variant="lightBtn">Button 1</Button>
          <Link href="#" variant="light">
            Link 2
          </Link>
          <CustomLink variant="light" href="#" arrow={true}>
            Link 3
          </CustomLink>
        </HStack>
        <HStack spacing="6" bg="primary.pureblack" p="6">
          <Button variant="darkBtn">Button 4</Button>
          <Link href="#" variant="dark">
            Link 5
          </Link>
          <CustomLink variant="dark" href="#" arrow={true}>
            View the stories
          </CustomLink>
        </HStack>
      </Box>
    </Box>
  )
}

export default DesignSystem
