import { Box, Text } from '@chakra-ui/layout'
import Head from 'next/head'

import Layout from '../components/Layout'
import { getStoriesPage } from '../graphql/queries/getStoriesPage'

export const getStaticProps = async () => {
  const { page, stories, featuredStory } = await getStoriesPage()

  return {
    props: {
      page,
      stories,
      featuredStory,
    },
  }
}

const Features = ({ page }) => {
  return (
    <Layout
      data={{
        header: page.header,
        footer: page.footer,
      }}
    >
      <Head>
        <title>Yes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box bg="blue.100">
        <Box bg="red.100" maxW="800px" mx="auto">
          <Text>Features page</Text>
        </Box>
      </Box>
    </Layout>
  )
}

export default Features
