import { Box, Flex } from '@chakra-ui/layout'
import Head from 'next/head'

import Hero from '../components/Hero'
import Layout from '../components/Layout'
import { getHomePage } from '../graphql/queries/getHomePage'

export const getStaticProps = async () => {
  const { page } = await getHomePage()

  return {
    props: {
      page,
    },
  }
}

export default function Home({ page }) {
  const heroes = page?.heroes ?? []

  console.log(page)
  return (
    <Layout
      data={{
        header: page.header,
        footer: page.footer,
      }}
    >
      <Head>
        <title>Next Chakra UI Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex direction="column">
        <Box bg="gray.300" maxW="container.lg2" mx="auto" w="full">
          {heroes.map((hero, index) => (
            <Hero
              key={index}
              image={hero.image}
              themeColor={hero.theme}
              title={hero.title}
              subtitle={hero.subtitle}
              link={hero.link}
              contentSide={hero.contentSide}
            />
          ))}
        </Box>
      </Flex>
    </Layout>
  )
}
