import { Box, Text } from '@chakra-ui/layout'
import Head from 'next/head'
import PropTypes from 'prop-types'

import Layout from '../components/Layout'
import { getStoriesPage } from '../graphql/queries/getStoriesPage'

export const getStaticProps = async () => {
  const { page } = await getStoriesPage()

  return {
    props: {
      page,
    },
  }
}

const Pricing = ({ page }) => {
  return (
    <Layout
      data={{
        header: page.header,
        footer: page.footer,
      }}
    >
      <Head>
        <title>Yes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box bg="blue.100">
        <Box maxW="800px" mx="auto">
          <Text>Pricing Page</Text>
        </Box>
      </Box>
    </Layout>
  )
}

Pricing.propTypes = {
  page: PropTypes.shape({
    footer: PropTypes.object.isRequired,
    header: PropTypes.object.isRequired,
  }).isRequired,
}

export default Pricing
