import { Box, Text } from '@chakra-ui/layout'
import Head from 'next/head'
import PropTypes from 'prop-types'

import Banner from '../components/Banner'
import Hero from '../components/Hero'
import Layout from '../components/Layout'
import { getPricingPage } from '../graphql/queries/pages/getPricingPage'

export const getStaticProps = async () => {
  const { page } = await getPricingPage()

  return {
    props: {
      page,
    },
  }
}

const Pricing = ({ page }) => {
  console.log(page)
  const hero = page?.heroes[0] ?? {}
  const banner = page?.banner ?? {}
  const isBannerDisplayed = page?.isBannerDisplayed ?? false

  return (
    <Layout
      data={{
        header: page.header,
        footer: page.footer,
      }}
    >
      <Head>
        <title>Yes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg="white">
        {hero && (
          <Hero
            title={hero.title}
            subtitle={hero.subtitle}
            contentSide={hero.contentSide}
            themeColor={hero.theme}
            image={hero.image}
          />
        )}

        <Box px="6" py="16">
          <Text>The Features</Text>
        </Box>

        {isBannerDisplayed && (
          <Banner
            title={banner.title}
            link={banner.link}
            backgroundImage={banner.backgroundImage}
          />
        )}
      </Box>
    </Layout>
  )
}

Pricing.propTypes = {
  page: PropTypes.shape({
    footer: PropTypes.object.isRequired,
    header: PropTypes.object.isRequired,
    heroes: PropTypes.array,
    banner: PropTypes.object,
    isBannerDisplayed: PropTypes.bool.isRequired,
  }),
}

export default Pricing
