import {
  Box,
  Divider,
  Flex,
  Heading,
  SimpleGrid,
  Text,
} from '@chakra-ui/layout'
import Head from 'next/head'
import NextImage from 'next/image'

import Arrow from '../assets/arrow'
import Footer from '../components/Footer'
import Header from '../components/Header'
import CustomLink from '../components/utils/CustomLink'
import { getStoriesPage } from '../graphql/queries/getStoriesPage'

export const getStaticProps = async () => {
  const { page, stories, featuredStory } = await getStoriesPage() // your fetch function here

  return {
    props: {
      page,
      stories,
      featuredStory,
    },
  }
}

export default function Stories({ stories = [], featuredStory }) {
  return (
    <Box>
      <Head>
        <title>Next Chakra UI Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex role="main" direction="column" align="center">
        <Header />
        <Box maxW="container.xl2" bg="red.100" w="full">
          <Box>
            <Box
              w="full"
              bg="red.100"
              h={{ base: 'full', xl: 'full' }}
              pos="relative"
            >
              <NextImage
                src={featuredStory[0].featuredPhoto.url}
                width={featuredStory[0].featuredPhoto.width}
                height={featuredStory[0].featuredPhoto.height}
                layout="responsive"
              />
            </Box>
          </Box>
          <SimpleGrid minChildWidth="300px" spacing="0">
            {stories.map((story) => (
              <Box bg="gray.800" key={story.id} color="white" pos="relative">
                <Box w="full" h="500px" zIndex="base" pos="relative">
                  <NextImage
                    src={story.photo.url}
                    layout="fill"
                    objectFit="cover"
                  />
                  <Box
                    w="full"
                    zIndex="overlay"
                    pos="absolute"
                    bottom="0"
                    px="10"
                    py="40"
                    pb="10"
                    bgGradient="linear-gradient(0deg, rgba(0,0,0,0.7) 0%, rgba(0,0,0,0) 100%)"
                  >
                    <Text color="white">{story.date}</Text>
                    <Heading as="h3" variant="h3">
                      {story.title}
                    </Heading>
                    <Text color="white">By {story.author.name}</Text>
                    <Divider borderColor="white" opacity="0.2" my="4" />
                    <Flex justify="space-between">
                      <CustomLink href={`/stories/${story.slug}`}>
                        Read story
                      </CustomLink>
                      <Box w="42px">
                        <Arrow />
                      </Box>
                    </Flex>
                  </Box>
                </Box>
              </Box>
            ))}
          </SimpleGrid>
        </Box>
      </Flex>

      <Footer />
    </Box>
  )
}
